### ISSUE TITLE
get_reports() giving posts rather than the report

### ISSUE THREAD

**Issue by Coding-Cactus** [mat-1/repl-talk-api#15] opened 2020-11-16 21:45 UTC
Hi @mat-1 I'm so sorry to keep bothering you but, I'm just confused why `get_reports()` is returning `Post`s and `Comment`s instead of the actual `Report`. How do I get the `Report` from the `Post`?
![image](https://user-images.githubusercontent.com/65423356/99311716-e5a39900-2854-11eb-8bcd-6052c571750f.png)

**Comment by mat-1** [comment] 2020-11-16 23:47
Doing `async for` gets the posts instead of reports, just do `for report in await client.get_reports(resolved=False)` instead
https://github.com/mat-1/repl-talk-api/blob/master/repltalk/__init__.py#L198

**Comment by mat-1** [comment] 2020-11-16 23:48
Wait that's probably not intended behavior i'll fix it in a minute

**Comment by mat-1** [comment] 2020-11-16 23:50
Fixed by https://github.com/mat-1/repl-talk-api/commit/300ba400f03b4f073ddde133732972d09935e264

**Closed as completed by mat-1** 2020-11-16 23:50 UTC
